import { Translation } from 'primeng/api';

export const PRIMENG_ARABIC: Translation = {
  startsWith: 'يبدأ بـ',
  contains: 'يحتوي على',
  notContains: 'لا يحتوي على',
  endsWith: 'ينتهي بـ',
  equals: 'يساوي',
  notEquals: 'لا يساوي',
  noFilter: 'بدون تصفية',
  lt: 'أقل من',
  lte: 'أقل من أو يساوي',
  gt: 'أكبر من',
  gte: 'أكبر من أو يساوي',
  is: 'هو',
  isNot: 'ليس',
  before: 'قبل',
  after: 'بعد',
  dateIs: 'التاريخ هو',
  dateIsNot: 'التاريخ ليس',
  dateBefore: 'التاريخ قبل',
  dateAfter: 'التاريخ بعد',
  clear: 'مسح',
  apply: 'تطبيق',
  matchAll: 'مطابقة الكل',
  matchAny: 'مطابقة أي',
  addRule: 'إضافة قاعدة',
  removeRule: 'إزالة قاعدة',
  accept: 'موافق',
  reject: 'إلغاء',
  choose: 'اختر',
  upload: 'رفع',
  cancel: 'إلغاء',
  dayNames: [
    'الأحد',
    'الإثنين',
    'الثلاثاء',
    'الأربعاء',
    'الخميس',
    'الجمعة',
    'السبت',
  ],
  dayNamesShort: ['أحد', 'إثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'سبت'],
  dayNamesMin: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
  monthNames: [
    'يناير',
    'فبراير',
    'مارس',
    'أبريل',
    'مايو',
    'يونيو',
    'يوليو',
    'أغسطس',
    'سبتمبر',
    'أكتوبر',
    'نوفمبر',
    'ديسمبر',
  ],
  monthNamesShort: [
    'يناير',
    'فبراير',
    'مارس',
    'أبريل',
    'مايو',
    'يونيو',
    'يوليو',
    'أغسطس',
    'سبتمبر',
    'أكتوبر',
    'نوفمبر',
    'ديسمبر',
  ],
  dateFormat: 'dd/mm/yy',
  firstDayOfWeek: 6, // 0 is Sunday, 6 is Saturday (Standard in most Arab countries)
  today: 'اليوم',
  weekHeader: 'أسبوع',
  weak: 'ضعيف',
  medium: 'متوسط',
  strong: 'قوي',
  passwordPrompt: 'أدخل كلمة المرور',
  emptyMessage: 'لا توجد نتائج',
  emptyFilterMessage: 'لا توجد نتائج تطابق بحثك',
  pending: 'قيد الانتظار',
  fileSizeTypes: ['بايت', 'كيلوبايت', 'ميجابايت', 'جيجابايت', 'تيرابايت'],

  // Accessibility & ARIA Labels (Important for screen readers)
  aria: {
    trueLabel: 'صحيح',
    falseLabel: 'خاطئ',
    nullLabel: 'غير محدد',
    star: 'نجمة',
    stars: 'نجوم',
    selectAll: 'تحديد الكل',
    unselectAll: 'إلغاء تحديد الكل',
    close: 'إغلاق',
    previous: 'السابق',
    next: 'التالي',
    navigation: 'تنسقل',
    scrollTop: 'انتقل للأعلى',
    moveTop: 'تحرك للأعلى',
    moveUp: 'تحرك لأعلى',
    moveDown: 'تحرك لأسفل',
    moveBottom: 'تحرك للأسفل',
    moveToTarget: 'انقل للهدف',
    moveToSource: 'انقل للمصدر',
    moveAllToTarget: 'انقل الكل للهدف',
    moveAllToSource: 'انقل الكل للمصدر',
    pageLabel: 'صفحة {page}',
    firstPageLabel: 'الصفحة الأولى',
    lastPageLabel: 'الصفحة الأخيرة',
    nextPageLabel: 'الصفحة التالية',
    previousPageLabel: 'الصفحة السابقة',
    rowsPerPageLabel: 'صفوف لكل صفحة',
    jumpToPageDropdownLabel: 'انتقل إلى قائمة الصفحات',
    jumpToPageInputLabel: 'انتقل إلى إدخال الصفحة',
    selectRow: 'تم تحديد الصف',
    unselectRow: 'تم إلغاء تحديد الصف',
    expandRow: 'توسيع الصف',
    collapseRow: 'طي الصف',
    showFilterMenu: 'إظهار قائمة التصفية',
    hideFilterMenu: 'إخفاء قائمة التصفية',
    filterOperator: 'عامل التصفية',
    filterConstraint: 'قيد التصفية',
    editRow: 'تحرير الصف',
    saveEdit: 'حفظ التحرير',
    cancelEdit: 'إلغاء التحرير',
    listView: 'عرض القائمة',
    gridView: 'عرض الشبكة',
    slide: 'شريحة',
    slideNumber: '{slideNumber}',
    zoomImage: 'تكبير الصورة',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    rotateRight: 'تدوير لليمين',
    rotateLeft: 'تدوير لليسار',
  },
};
